server:
  port: 8081

spring:
  application:
    # 应用名称
    name: ai-learning-profile-backend
  datasource:
    url: jdbc:mysql://localhost:3306/learning_profile?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver